Vagrant.configure("2") do |config|
    # Define the virtual machine box and its properties
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "forwarded_port", guest: 3000, host: 3000  # Forward port for Vue Storefront development
  
    config.vm.define "server-1" do |server_1|
      server_1.vm.network "private_network", ip: "192.168.56.12"
      server_1.vm.hostname = "server-1"

      # Specify the machine setup and provisioning using Ansible
      server_1.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "ansible/main.yml" # Specify the path to your Ansible playbook
        ansible.inventory_path = "ansible/inventory"
      end
  end

    config.vm.define "server-2" do |server_2|
      server_2.vm.network "private_network", ip: "192.168.56.13"
      server_2.vm.hostname = "server-2"

        # Specify the machine setup and provisioning using Ansible
      server_2.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "ansible/main.yml" # Specify the path to your Ansible playbook
        ansible.inventory_path = "ansible/inventory"
      end
  end

    config.vm.define "server-3" do |server_3|
      server_3.vm.network "private_network", ip: "192.168.56.14"
      server_3.vm.hostname = "server-3"

      # Specify the machine setup and provisioning using Ansible
      server_3.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "ansible/main.yml" # Specify the path to your Ansible playbook
        ansible.inventory_path = "ansible/inventory"
    end
end
  
  